apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: wazuh-indexer
  name: wazuh-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wazuh-indexer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: wazuh-indexer
    spec:
      containers:
      - env:
        - name: OPENSEARCH_JAVA_OPTS
          value: -Xms512m -Xmx512m
        image: wazuh/wazuh-indexer:4.3.1
        imagePullPolicy: ""
        name: wazuh-indexer
        ports:
        - containerPort: 9200
        resources: {}
      hostname: wazuh.indexer
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
