apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f build-from-sources.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f build-from-sources.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_PASSWORD
          value: admin
        - name: ELASTICSEARCH_USERNAME
          value: admin
        - name: SERVER_SSL_CERTIFICATE
          value: /usr/share/kibana/config/opendistroforelasticsearch.example.org.cert
        - name: SERVER_SSL_ENABLED
          value: "true"
        - name: SERVER_SSL_KEY
          value: /usr/share/kibana/config/opendistroforelasticsearch.example.org.key
        image: wazuh/wazuh-kibana-odfe:dev-version
        imagePullPolicy: ""
        name: kibana
        ports:
        - containerPort: 5601
        resources: {}
      hostname: kibana
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
