apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f build-from-sources.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: wazuh
  name: wazuh
spec:
  ports:
  - name: "1514"
    port: 1514
    targetPort: 1514
  - name: "1515"
    port: 1515
    targetPort: 1515
  - name: "514"
    port: 514
    protocol: UDP
    targetPort: 514
  - name: "55000"
    port: 55000
    targetPort: 55000
  selector:
    io.kompose.service: wazuh
status:
  loadBalancer: {}
